language: android
android:
  components:
    - build-tools-23.0.1
    - android-23

before_install:
 - chmod +x gradlew
 - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null